# Generated by Django 5.1.1 on 2024-10-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kinase",
            fields=[
                (
                    "kinase",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("accession", models.CharField(max_length=255)),
                ("fasta", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=255)),
                ("frequency", models.IntegerField()),
                (
                    "kinase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequncy_kinase",
                        to="kinome.kinase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                (
                    "kinase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains_kinase",
                        to="kinome.kinase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistanceMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site1", models.CharField(max_length=25)),
                ("site2", models.CharField(max_length=25)),
                ("distance", models.DecimalField(decimal_places=25, max_digits=50)),
                (
                    "kinase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distance_matrix_kinase",
                        to="kinome.kinase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Corsstalk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site1", models.CharField(max_length=25)),
                ("site2", models.CharField(max_length=25)),
                ("n_00", models.IntegerField()),
                ("n_01", models.IntegerField()),
                ("n_10", models.IntegerField()),
                ("n_11", models.IntegerField()),
                ("p_value", models.FloatField()),
                (
                    "function_site1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "function_site2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kinase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crosstalk_kinase",
                        to="kinome.kinase",
                    ),
                ),
            ],
        ),
    ]
