# Generated by Django 5.1.2 on 2024-10-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinome', '0003_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamName',
            fields=[
                ('family', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_family', to='kinome.famname'),
        ),
    ]
