# Generated by Django 5.1.2 on 2024-10-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinome', '0004_famname_alter_family_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_famname', to='kinome.famname'),
        ),
    ]
